services:
  _defaults:
    autowire: true
    autoconfigure: true

  SumoCoders\OAuthBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/SumoCodersOAuthBundle.php'
